// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_crrMz5QMZuA5ynpnWLJnxItabP7b1vs',
    appId: '1:172547666138:web:0adf0d57e7f3ca3e7175e3',
    messagingSenderId: '172547666138',
    projectId: 'hostel-reservation-1',
    authDomain: 'hostel-reservation-1.firebaseapp.com',
    storageBucket: 'hostel-reservation-1.firebasestorage.app',
    measurementId: 'G-GRX4LT5SRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrx81HKMKK10gOBtaEMvQBbefDLbN_ulY',
    appId: '1:172547666138:android:baa3b13aa914d6347175e3',
    messagingSenderId: '172547666138',
    projectId: 'hostel-reservation-1',
    storageBucket: 'hostel-reservation-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNxOyVm6CcqdjqLsqlyebFK8DPKrZ3p3U',
    appId: '1:172547666138:ios:bf3cb9131eb5a94d7175e3',
    messagingSenderId: '172547666138',
    projectId: 'hostel-reservation-1',
    storageBucket: 'hostel-reservation-1.firebasestorage.app',
    iosBundleId: 'com.example.hostelReservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNxOyVm6CcqdjqLsqlyebFK8DPKrZ3p3U',
    appId: '1:172547666138:ios:bf3cb9131eb5a94d7175e3',
    messagingSenderId: '172547666138',
    projectId: 'hostel-reservation-1',
    storageBucket: 'hostel-reservation-1.firebasestorage.app',
    iosBundleId: 'com.example.hostelReservation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_crrMz5QMZuA5ynpnWLJnxItabP7b1vs',
    appId: '1:172547666138:web:92e8a285a1b7ef087175e3',
    messagingSenderId: '172547666138',
    projectId: 'hostel-reservation-1',
    authDomain: 'hostel-reservation-1.firebaseapp.com',
    storageBucket: 'hostel-reservation-1.firebasestorage.app',
    measurementId: 'G-S3P1EVKCNN',
  );
}
